export const MAX_COLLISION_STREAMING_RADIUS = 64;
export const MAX_COLLISION_BUILDS_PER_FRAME = 64;
export const MAX_COLLIDER_CHUNKS = 4096;
export const MAX_COLLISION_BINS_PER_CHUNK = 16384;

export const COLLISION_RETRY_BASE_MS = 250;
export const COLLISION_RETRY_MAX_MS = 5000;
