const DROP_COUNT = 1800;
const SNOW_FLAKE_COUNT = 3600;
const SANDSTORM_PARTICLE_COUNT = 9800;
const HARD_SPLASH_COUNT = 220;
const WATER_SPLASH_COUNT = 120;
const RAIN_AREA = 48;
const SNOW_NEAR_AREA = 28;
const SNOW_MID_AREA = 36;
const SNOW_FAR_AREA = 46;
const SANDSTORM_NEAR_COUNT = 3900;
const SANDSTORM_MID_COUNT = 3400;
const SANDSTORM_FAR_COUNT = 2500;
const SPLASH_AREA = 36;
const REPOSITION_DISTANCE = 8;
const WATER_DEPTH_EPSILON = 0.035;
const WATER_MASK_EPSILON = 0.05;
const TAU = Math.PI * 2;
export {
  DROP_COUNT,
  HARD_SPLASH_COUNT,
  RAIN_AREA,
  REPOSITION_DISTANCE,
  SANDSTORM_FAR_COUNT,
  SANDSTORM_MID_COUNT,
  SANDSTORM_NEAR_COUNT,
  SANDSTORM_PARTICLE_COUNT,
  SNOW_FAR_AREA,
  SNOW_FLAKE_COUNT,
  SNOW_MID_AREA,
  SNOW_NEAR_AREA,
  SPLASH_AREA,
  TAU,
  WATER_DEPTH_EPSILON,
  WATER_MASK_EPSILON,
  WATER_SPLASH_COUNT
};
