const STRIKE_COUNT = 32;
const IMPACT_ROOT_COUNT = 6;
const STRIKE_AREA = 48;
const REPOSITION_DISTANCE = 8;
const SURFACE_OFFSET = 0.09;
const IMPACT_SURFACE_OFFSET = 0.045;
const WATER_DEPTH_EPSILON = 0.035;
const WATER_MASK_EPSILON = 0.05;
const DEFAULT_SEED = 1470419143;
export {
  DEFAULT_SEED,
  IMPACT_ROOT_COUNT,
  IMPACT_SURFACE_OFFSET,
  REPOSITION_DISTANCE,
  STRIKE_AREA,
  STRIKE_COUNT,
  SURFACE_OFFSET,
  WATER_DEPTH_EPSILON,
  WATER_MASK_EPSILON
};
